# Generated by Django 5.2.2 on 2025-06-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentmanager_remove_post_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
